# ========================================================
# = data for some of the figures for imputation analysis =
# ========================================================

# 1. histogram for MAF in the imputation ready panel
# ============================================================

module load R
Rscript -e 'maf.counts <- rep(0, 100); for (i in 1:18) { this.maf <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/chr", i, ".QC.final.frq", sep = ""), header = TRUE, as.is = TRUE)[, 5]; this.hist <- hist(this.maf, breaks = seq(0, 0.5, 0.005), plot = FALSE); maf.counts <- maf.counts + this.hist$counts }; last.hist <- this.hist; save(maf.counts, last.hist, file = "all.maf.hist.RData");'

Rscript -e 'maf.counts <- rep(0, 100); snp.chip <- read.table("/mnt/research/qgg/share/dingr/swim_data/PorcineSNP50K.txt", header = FALSE, as.is = TRUE)[, 1]; for (i in 1:18) { this.maf <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/chr", i, ".QC.final.frq", sep = ""), header = TRUE, as.is = TRUE); rownames(this.maf) <- this.maf[, 2]; this.hist <- hist(this.maf[na.omit(match(snp.chip, this.maf[, 2])), 5], , breaks = seq(0, 0.5, 0.005), plot = FALSE); maf.counts <- maf.counts + this.hist$counts }; last.hist <- this.hist; save(maf.counts, last.hist, file = "chip.maf.hist.RData");'

# 2. SRA data table
# ============================================================

tail -n+2 SWIM_BreedInfo.txt | awk '$1 ~ /^SRS/ || $1 ~ /^ERS/ { print $1 }' | sort -k1,1 | join -t $'\t' - ~/qgg/resource/SRAdb/SRA_Accessions.tab.latest.sample.sorted | ~/qgg/software/bedtools-2.29.2/bin/bedtools groupby -g 1 -c 2 -o collapse | join -t $'\t' - sra.sample.prj.sorted | join -t $'\t' <(tail -n+2 SWIM_BreedInfo.txt | awk '{print $1"\t"$2"\t"$3}' | sort -k1,1) - > sra.sample.prj.info

# 3. imputation accuracy
# ============================================================

module load R
Rscript -e 'accu <- matrix(0, nrow = 50, ncol = 3); snp.count <- numeric(50); mean.accu <- numeric(3); for (i in 1:18) { this.chr.accu <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/accuracy_target_maf.impute5.mafM0.chr", i, ".ref1.LR550.txt", sep = ""), header = TRUE, as.is = TRUE); this.maf.bin <- factor(cut(this.chr.accu$maf, breaks = seq(0, 0.5, 0.01), include.lowest = TRUE)); accu[, 1] = accu[, 1] + sapply(split(this.chr.accu$concRate, this.maf.bin), sum); accu[, 2] = accu[, 2] + sapply(split(this.chr.accu$NRC, this.maf.bin), sum); accu[, 3] = accu[, 3] + sapply(split(this.chr.accu$r_calc^2, this.maf.bin), sum); snp.count <- snp.count + table(this.maf.bin); }; mean.accu <- colSums(accu)/sum(snp.count); accu[, 1] = accu[, 1]/snp.count; accu[, 2] = accu[, 2]/snp.count; accu[, 3] = accu[, 3]/snp.count; save(accu, mean.accu, file = "impute5.lr550.RData");' &

Rscript -e 'accu <- matrix(0, nrow = 50, ncol = 3); snp.count <- numeric(50); mean.accu <- numeric(3); for (i in 1:18) { this.chr.accu <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/accuracy_target_maf.impute5.mafM0.chr", i, ".ref2.DLY550.txt", sep = ""), header = TRUE, as.is = TRUE); this.maf.bin <- factor(cut(this.chr.accu$maf, breaks = seq(0, 0.5, 0.01), include.lowest = TRUE)); accu[, 1] = accu[, 1] + sapply(split(this.chr.accu$concRate, this.maf.bin), sum); accu[, 2] = accu[, 2] + sapply(split(this.chr.accu$NRC, this.maf.bin), sum); accu[, 3] = accu[, 3] + sapply(split(this.chr.accu$r_calc^2, this.maf.bin), sum); snp.count <- snp.count + table(this.maf.bin); }; mean.accu <- colSums(accu)/sum(snp.count); accu[, 1] = accu[, 1]/snp.count; accu[, 2] = accu[, 2]/snp.count; accu[, 3] = accu[, 3]/snp.count; save(accu, mean.accu, file = "impute5.dly550.RData");' &

Rscript -e 'accu <- matrix(0, nrow = 50, ncol = 3); snp.count <- numeric(50); mean.accu <- numeric(3); for (i in 1:18) { this.chr.accu <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/accuracy_target_maf.impute5.mafM0.chr", i, ".ref3.noDLY550.txt", sep = ""), header = TRUE, as.is = TRUE); this.maf.bin <- factor(cut(this.chr.accu$maf, breaks = seq(0, 0.5, 0.01), include.lowest = TRUE)); accu[, 1] = accu[, 1] + sapply(split(this.chr.accu$concRate, this.maf.bin), sum); accu[, 2] = accu[, 2] + sapply(split(this.chr.accu$NRC, this.maf.bin), sum); accu[, 3] = accu[, 3] + sapply(split(this.chr.accu$r_calc^2, this.maf.bin), sum); snp.count <- snp.count + table(this.maf.bin); }; mean.accu <- colSums(accu)/sum(snp.count); accu[, 1] = accu[, 1]/snp.count; accu[, 2] = accu[, 2]/snp.count; accu[, 3] = accu[, 3]/snp.count; save(accu, mean.accu, file = "impute5.nodly550.RData");' &

Rscript -e 'accu <- matrix(0, nrow = 50, ncol = 3); snp.count <- numeric(50); mean.accu <- numeric(3); for (i in 1:18) { this.chr.accu <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/accuracy_target_maf.minimac4.mafM0.chr", i, ".ref1.LR550.txt", sep = ""), header = TRUE, as.is = TRUE); this.maf.bin <- factor(cut(this.chr.accu$maf, breaks = seq(0, 0.5, 0.01), include.lowest = TRUE)); accu[, 1] = accu[, 1] + sapply(split(this.chr.accu$concRate, this.maf.bin), sum); accu[, 2] = accu[, 2] + sapply(split(this.chr.accu$NRC, this.maf.bin), sum); accu[, 3] = accu[, 3] + sapply(split(this.chr.accu$r_calc^2, this.maf.bin), sum); snp.count <- snp.count + table(this.maf.bin); }; mean.accu <- colSums(accu)/sum(snp.count); accu[, 1] = accu[, 1]/snp.count; accu[, 2] = accu[, 2]/snp.count; accu[, 3] = accu[, 3]/snp.count; save(accu, mean.accu, file = "minimac4.lr550.RData");' &

Rscript -e 'accu <- matrix(0, nrow = 50, ncol = 3); snp.count <- numeric(50); mean.accu <- numeric(3); for (i in 1:18) { this.chr.accu <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/accuracy_target_maf.minimac4.mafM0.chr", i, ".ref2.DLY550.txt", sep = ""), header = TRUE, as.is = TRUE); this.maf.bin <- factor(cut(this.chr.accu$maf, breaks = seq(0, 0.5, 0.01), include.lowest = TRUE)); accu[, 1] = accu[, 1] + sapply(split(this.chr.accu$concRate, this.maf.bin), sum); accu[, 2] = accu[, 2] + sapply(split(this.chr.accu$NRC, this.maf.bin), sum); accu[, 3] = accu[, 3] + sapply(split(this.chr.accu$r_calc^2, this.maf.bin), sum); snp.count <- snp.count + table(this.maf.bin); }; mean.accu <- colSums(accu)/sum(snp.count); accu[, 1] = accu[, 1]/snp.count; accu[, 2] = accu[, 2]/snp.count; accu[, 3] = accu[, 3]/snp.count; save(accu, mean.accu, file = "minimac4.dly550.RData");' &

Rscript -e 'accu <- matrix(0, nrow = 50, ncol = 3); snp.count <- numeric(50); mean.accu <- numeric(3); for (i in 1:18) { this.chr.accu <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/accuracy_target_maf.minimac4.mafM0.chr", i, ".ref3.noDLY550.txt", sep = ""), header = TRUE, as.is = TRUE); this.maf.bin <- factor(cut(this.chr.accu$maf, breaks = seq(0, 0.5, 0.01), include.lowest = TRUE)); accu[, 1] = accu[, 1] + sapply(split(this.chr.accu$concRate, this.maf.bin), sum); accu[, 2] = accu[, 2] + sapply(split(this.chr.accu$NRC, this.maf.bin), sum); accu[, 3] = accu[, 3] + sapply(split(this.chr.accu$r_calc^2, this.maf.bin), sum); snp.count <- snp.count + table(this.maf.bin); }; mean.accu <- colSums(accu)/sum(snp.count); accu[, 1] = accu[, 1]/snp.count; accu[, 2] = accu[, 2]/snp.count; accu[, 3] = accu[, 3]/snp.count; save(accu, mean.accu, file = "minimac4.nodly550.RData");' &

Rscript -e 'accu <- matrix(0, nrow = 50, ncol = 3); snp.count <- numeric(50); mean.accu <- numeric(3); for (i in 1:18) { this.chr.accu <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/accuracy_target_maf.beagle.mafM0.chr", i, ".ref1.LR550.txt", sep = ""), header = TRUE, as.is = TRUE); this.maf.bin <- factor(cut(this.chr.accu$maf, breaks = seq(0, 0.5, 0.01), include.lowest = TRUE)); accu[, 1] = accu[, 1] + sapply(split(this.chr.accu$concRate, this.maf.bin), sum); accu[, 2] = accu[, 2] + sapply(split(this.chr.accu$NRC, this.maf.bin), sum); accu[, 3] = accu[, 3] + sapply(split(this.chr.accu$r_calc^2, this.maf.bin), sum); snp.count <- snp.count + table(this.maf.bin); }; mean.accu <- colSums(accu)/sum(snp.count); accu[, 1] = accu[, 1]/snp.count; accu[, 2] = accu[, 2]/snp.count; accu[, 3] = accu[, 3]/snp.count; save(accu, mean.accu, file = "beagle.lr550.RData");' &

Rscript -e 'accu <- matrix(0, nrow = 50, ncol = 3); snp.count <- numeric(50); mean.accu <- numeric(3); for (i in 1:18) { this.chr.accu <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/accuracy_target_maf.beagle.mafM0.chr", i, ".ref2.DLY550.txt", sep = ""), header = TRUE, as.is = TRUE); this.maf.bin <- factor(cut(this.chr.accu$maf, breaks = seq(0, 0.5, 0.01), include.lowest = TRUE)); accu[, 1] = accu[, 1] + sapply(split(this.chr.accu$concRate, this.maf.bin), sum); accu[, 2] = accu[, 2] + sapply(split(this.chr.accu$NRC, this.maf.bin), sum); accu[, 3] = accu[, 3] + sapply(split(this.chr.accu$r_calc^2, this.maf.bin), sum); snp.count <- snp.count + table(this.maf.bin); }; mean.accu <- colSums(accu)/sum(snp.count); accu[, 1] = accu[, 1]/snp.count; accu[, 2] = accu[, 2]/snp.count; accu[, 3] = accu[, 3]/snp.count; save(accu, mean.accu, file = "beagle.dly550.RData");' &

Rscript -e 'accu <- matrix(0, nrow = 50, ncol = 3); snp.count <- numeric(50); mean.accu <- numeric(3); for (i in 1:18) { this.chr.accu <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/accuracy_target_maf.beagle.mafM0.chr", i, ".ref3.noDLY550.txt", sep = ""), header = TRUE, as.is = TRUE); this.maf.bin <- factor(cut(this.chr.accu$maf, breaks = seq(0, 0.5, 0.01), include.lowest = TRUE)); accu[, 1] = accu[, 1] + sapply(split(this.chr.accu$concRate, this.maf.bin), sum); accu[, 2] = accu[, 2] + sapply(split(this.chr.accu$NRC, this.maf.bin), sum); accu[, 3] = accu[, 3] + sapply(split(this.chr.accu$r_calc^2, this.maf.bin), sum); snp.count <- snp.count + table(this.maf.bin); }; mean.accu <- colSums(accu)/sum(snp.count); accu[, 1] = accu[, 1]/snp.count; accu[, 2] = accu[, 2]/snp.count; accu[, 3] = accu[, 3]/snp.count; save(accu, mean.accu, file = "beagle.nodly550.RData");' &

# all 
module load R
Rscript -e 'accu <- matrix(0, nrow = 50, ncol = 3); snp.count <- numeric(50); mean.accu <- numeric(3); for (i in 1:18) { this.chr.accu <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/accuracy_maf.swim_remove100LR.chr", i, ".txt", sep = ""), header = TRUE, as.is = TRUE); this.maf.bin <- factor(cut(this.chr.accu$maf, breaks = seq(0, 0.5, 0.01), include.lowest = TRUE)); accu[, 1] = accu[, 1] + sapply(split(this.chr.accu$concRate, this.maf.bin), sum); accu[, 2] = accu[, 2] + sapply(split(this.chr.accu$NRC, this.maf.bin), sum); accu[, 3] = accu[, 3] + sapply(split(this.chr.accu$r_calc^2, this.maf.bin), sum); snp.count <- snp.count + table(this.maf.bin); }; mean.accu <- colSums(accu)/sum(snp.count); accu[, 1] = accu[, 1]/snp.count; accu[, 2] = accu[, 2]/snp.count; accu[, 3] = accu[, 3]/snp.count; save(accu, mean.accu, file = "impute5.all.RData");' &

Rscript -e 'accu <- matrix(0, nrow = 50, ncol = 3); snp.count <- numeric(50); mean.accu <- numeric(3); for (i in 1:18) { this.chr.accu <- read.table(paste("/mnt/research/qgg/share/dingr/swim_data/accuracy_maf.pharp.chr", i, ".txt", sep = ""), header = TRUE, as.is = TRUE); this.maf.bin <- factor(cut(this.chr.accu$maf, breaks = seq(0, 0.5, 0.01), include.lowest = TRUE)); accu[, 1] = accu[, 1] + sapply(split(this.chr.accu$concRate, this.maf.bin), sum); accu[, 2] = accu[, 2] + sapply(split(this.chr.accu$NRC, this.maf.bin), sum); accu[, 3] = accu[, 3] + sapply(split(this.chr.accu$r_calc^2, this.maf.bin), sum); snp.count <- snp.count + table(this.maf.bin); }; mean.accu <- colSums(accu)/sum(snp.count); accu[, 1] = accu[, 1]/snp.count; accu[, 2] = accu[, 2]/snp.count; accu[, 3] = accu[, 3]/snp.count; save(accu, mean.accu, file = "pharp.RData");' &









